name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  run-tests:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: swift test

  # run-ui-tests:
  #   runs-on: macos-11
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Run UI Tests
  #     run: swift test
